### ISSUE TITLE
Requirement is pinned for PyEssent 0.13: requests==2.22.0

### ISSUE THREAD

**Issue by MartinHjelmare** [TheLastProject/PyEssent#8] opened 2020-11-16 12:22 UTC
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would release a new version where the pinning allows any higher version with just a minimum version set.

Thanks for your support of Home Assistant!

**Comment by TheLastProject** [comment] 2020-11-16 12:25
Duplicate of #7?

Ah, I see now, you want me to make a new release. Okay, can do.

**Comment by MartinHjelmare** [comment] 2020-11-16 13:34
Sorry about opening a new issue. Yes a new release would be great, and also if you can bump the version used in home assistant. Thanks!

**Comment by TheLastProject** [comment] 2020-11-16 13:56
Release 0.14 done with that change and https://github.com/home-assistant/core/pull/43282 made.

**Closed as completed by TheLastProject** 2020-11-16 13:56 UTC
